///////////////////////////////////////
// Import Dependencies
///////////////////////////////////////
const mongoose = require('./connection')
const Dessert = require('./dessert')

///////////////////////////////////////
// Seed Script code
/////////////////////////////////////
const db = mongoose.connection

db.on('open', () => {

    const startDesserts =[
       
        { name: 'Apple Pie', plantBased:false, vegetarian:true, dairyFree: false, hasMeat: false, glutenFree:false, ingredients:'2 unbaked pie shells, 3/4 cup sugar, 1/4 cup flour, 1/4 tsp cinnamon, 6 cups thinly sliced apples(about 6 apples), 2 Tbsp butter, 1/4 cup milk', directions:'Preheat oven to 425 degrees F. Sift sugar, flour, cinnamon together and add apples. Turn into unbaked pie shell in pie plate. Dot with butter. Cover with top pie shell andflute edged. Vent the top pie shell. Brush top pie shell with milk. Place tinfoil around edged to avoid burning. Bake 20 minutes then remove tinfoil and bake an additional 20-30 minutes.', note:''},
        { name: 'Nestle Chocolate Chip Cookies', plantBased:false, vegetarian:true, dairyFree: false, hasMeat: false, glutenFree: false, ingredients:'2 1/4 cups all-purpose flour, 1 teaspoon baking soda, 1 teaspoon salt, 1 cup (2 sticks) butter, softened, 3/4 cup granulated sugar, 3/4 cup packed brown sugar, 1 teaspoon vanilla extract, 2 large eggs, 2 cups (12-oz. pkg.) Nestlé Toll House Semi-Sweet Chocolate Morsels, 1 cup chopped nuts (if omitting, add 1-2 tablespoons of all-purpose flour)', directions:'1. Preheat oven to 375° F. 2. Combine flour, baking soda and salt in small bowl. Beat butter, granulated sugar, brown sugar and vanilla extract in large mixer bowl until creamy. Add eggs, one at a time, beating well after each addition. Gradually beat in flour mixture. Stir in morsels and nuts. Drop by rounded tablespoon onto ungreased baking sheets. 3. Bake for 9 to 11 minutes or until golden brown. Cool on baking sheets for 2 minutes; remove to wire racks to cool completely.', note:''},
        { name: 'Rolo Brownies', plantBased:false, vegetarian:true, dairyFree: false, hasMeat: false, glutenFree:false, ingredient:'Family Size Brownie mix (for 9 by 13 inch pan), eggs, oil, water (per brownie mix instructions), 12 ounce bag of Rolo candy, half unwrapped, 1 cup semi-sweet chocolate chips, 1/2 cup heavy whipping cream, 1 jar caramel sauce', directions:'Preheat the oven to 350 degrees and line the 9 by 13 baking dish with parchment paper. Follow the directions on the back of the brownie box to prepare the brownie batter then stir in 1/2 cup of semi-sweet chocolate chips. Pour half of the batter into the baking dish. Place the unwrapped Rolo candy all over the top of the brownie batter. Then pour the rest of the brownie batter over the Rolos. Bake in the preheated oven for 35-40 minutes. Allow to cool completely. To Make The Ganache , place the chocolate chips into a heat safe bowl. Using a small sauce pan, heat up the heavy whipping cream until it starts to simmer and steam.Pour heated heavy whipping cream over the chocolate chips. Allow to sit for one minute.Using a whisk, mix until smooth. Pour the Ganache over the cooled brownies. Allow the Ganache to harden for two hours in the fridge. Remove brownies from the refrigerator and lift the brownies out of the baking dish. Drizzle the caramel sauce all over the brownies.', note:''},
        { name: 'Black Bean Brownies', plantBased:true, vegetarian:true, dairyFree: true, hasMeat: false, glutenFree:false, ingredients: '1 1/2 cups black beans (1 15-oz can, drained and rinsed very well) (250g after draining) 2 tbsp cocoa powder (10g) 1/2 cup quick oats (40g) (See nutrition link below for substitutions) 1/4 tsp salt 1/3 cup pure maple syrup, honey, or agave (75g) pinch uncut stevia OR 2 tbsp sugar (or omit and increase maple syrup to 1/2 cup) 1/4 cup coconut or vegetable oil (40g) (See nutrition link for substitution notes) 2 tsp pure vanilla extract 1/2 tsp baking powder 1/2 cup to 2/3 cup vegan chocolate chips (Not optional. Omit at your own risk) optional: more chips, for presentation ', directions:'Preheat oven to 350 F. Combine all ingredients except chips in a good food processor, and blend until completely smooth. Really blend well. (A blender can work if you absolutely must, but the texture—and even the taste—will be much better in a food processor.) Stir in the chips, then pour into a greased 8 by 8 pan. Optional: sprinkle extra chocolate chips over the top. Cook the black bean brownies 15-18 minutes, then let cool at least 10 minutes before trying to cut. If they still look a bit undercooked, you can place them in the fridge overnight and they will magically firm up! Makes 9-12 brownies. The trick with these: serve them first, and then reveal the secret ingredient.', note:''},
        { name: 'Vegan Chocolate Chip Cookies', plantBased: true, vegetarian: true, dairyFree: true, hasMeat: false, glutenFree: false, ingredients:'3/4 cup refined coconut oil, 3/4 cup organic granulated sugar, 3/4 cup packed organic brown sugar, 1/2 cup unsweetened applesauce, 2 teaspoons vanilla, 2 1/2 cups all-purpose flour (see notes for gluten-free option), 1 teaspoon baking soda, 1 teaspoon salt, 1/2 teaspoon baking powder, 1 1/4 cups vegan chocolate chips', directions:'In a large bowl, add the coconut oil, granulated sugar, and brown sugar. Using a hand mixer (or a whisk) cream the oil and sugars together until fluffy. Add in the applesauce and vanilla, and mix well. Stir in the all-purpose flour, baking soda, baking powder, and salt until a dough forms. Lastly, fold in chocolate chips until well incorporated. Preheat oven to 350°F and line a baking sheet with parchment paper or a silicone mat. Keep in mind that this recipe makes 3 dozen so you will need to bake multiple batches. See notes for freezing options. Using a 1 tablespoon-sized scooper, drop mounds of dough onto the baking sheet 2 inches apart (we fit 12 on each sheet and baked these in 3 batches). No need to press them down. Place into the oven and bake for 13-14 minutes, or until the edges brown. The cookies will seem soft but do not worry, they will firm up while they cool. Allow the cookies to rest on the baking sheet for 1 minute after removing them from the oven and then carefully transfer them onto a cooling rack using a spatula. Cool until set and then dig in!', note:''},
        { name: 'Gluten Free Chocolate Cake', plantBased: false, vegetarian: true, dairyFree: true, hasMeat: false, glutenFree: true, ingredients:'2 1/4 cups Gluten-Free Measure for Measure Flour, 2 cups granulated sugar, 3/4 cup Dutch-process cocoa, 2 teaspoons baking powder, 1/2 teaspoon baking soda, 1 teaspoon salt, 4 large eggs, at room temperature, 3/4 cup vegetable oil, 2 teaspoons Pure Vanilla Extract, 1 1/4 cups brewed coffee or water, cool', directions:'1. Place a rack in the center of the oven. Preheat the oven to 350°F. 2. Lightly grease your choice of pan(s): one 9" x 13" pan, two 8" or 9" round cake pans, or the wells of two muffin pans (24 muffin cups). You can also line the muffin pans with papers, and lightly grease the insides of the papers using non-stick spray. 3. Whisk together the flour, sugar, cocoa, baking powder, baking soda, and salt. Set aside. 4. Whisk together the remaining ingredients, then pour the wet ingredients into the dry ingredients and stir until smooth. 5. Pour the batter into the prepared pans. 6. Bake the cake until the center feels firm when gently pressed, and a toothpick inserted in the center comes out clean — 42 to 50 minutes for a 9" x 13" pan; 30 to 36 minutes for 9" pans; 35 to 40 minutes for 8" pans, or 22 to 26 minutes for cupcakes. 7. Remove the cake from the oven. Allow it to cool completely in the pan, then loosen the edges with a knife and gently remove from the pan. Allow the cupcakes to cool in the pans for 5 minutes, then turn out onto a rack to cool completely. Store cake, covered, at room temperature for several days; freeze for longer storage.', note:''},
        { name: 'Old Fashioned Blueberry Pie', plantBased: false, vegetarian: true, dairyFree: false, hasMeat: true, glutenFree: false, ingredients:'2 pie shells, 3 cups fresh or frozen blueberries, 3/4c. sugar, 1 Tbsp. lemon juice, 3 Tbsp. ground quick-cooking tapioca, 1 Tbsp. butter, 1 tsp. milk of choice', directions:'1. Preheat oven to 400 degrees F. 2. In a bowl mix together blueberries, sugar, lemon juice and tapioca. Pour into the bottom pie shell in a pie pan. Cover with top pie shell, Brush milk on top crust. 3. Flute edges of pie and vent on top. Cover edged with tin foil. 4. Bake for 20 minutes, remove tin foil and bake an additional 20-30 minutes.', note:''},
        { name: 'Blueberry Boy Bait', plantBased: false, vegetarian: true, dairyFree: false, hasMeat: false, glutenFree: false, ingredients:'Butter for the pan, 2 cups all-purpose flour, 1 cup plus 3 tablespoons granulated sugar, 2 teaspoons baking powder, 1/4 teaspoon table salt, 2/3 cup vegetable oil, 1 cup milk, 2 large eggs, 3 cups blueberries, fresh or frozen, 1 teaspoon ground cinnamon', directions:'1. Preheat oven to 350° and butter a 9x13-inch baking pan. In a medium bowl, whisk together the flour, 1 cup of sugar, baking powder, and salt. Add the oil, milk, and eggs. Mix with an electric mixer for 3 minutes. Pour the batter into the prepared pan, then evenly sprinkle the blueberries on top. 2. In a small bowl, combine the remaining 3 tablespoons of sugar and 1 teaspoon of cinnamon, then sprinkle over the blueberries. 3. Bake until a cake tester inserted into the center comes out clean, about 50 minutes.', note:''},
        { name: 'Tiger Butter Fudge', plantBased: false, vegetarian: true, dairyFree: false, hasMeat: false, glutenFree: true, ingredients:'1 bag vanilla chips 11 oz, 1/2 cup creamy peanut butter, 1/2 cup semi-sweet chocolate chips', directions:'1. Line a bakers quarter sheet (or a 9 by 13 glass pan) with parchment paper or foil.2. Put semi sweet chocolate chips in a small glass bowl. Microwave for 1 minute and stir gently until smooth. Set aside. 3.Pour vanilla chips in a medium sized glass bowl. Microwave for 1 minute 30 seconds. Stir gently until smooth. Add peanut butter and stir until well combined and smooth.4. Pour vanilla-peanut butter mixture onto the prepared pan. Mixture will not reach the edges of the pan and that is OK. Once it is settled, take the melted semi sweet chocolate and pour it onto the vanilla-peanut butter mixture in lines. 5.Take a knife and run it the opposite direction of the chocolate lines you created, to achieve a swirl pattern. Run your knife through the mixture as much as you like, to create your desired swirl pattern. 6. Let cool either on the countertop or in the fridge. Cut into small squares. Store in an airtight container.', note:'' },
        { name: 'Vegan Mounds Bar', plantBased: true, vegetarian: true, dairyFree: true, hasMeat: false, glutenFree: true, ingredients:'1 1/2 cup unsweetened shredded coconut, 3 Tbsp. full fat coconut milk, 3 Tbsp. coconut oil, 2 Tbsp, agave, 1 1/4 cup vegan chocolate chips', directions:'1. Add the coconut, coconut milk, coconut oil, and agave, to a food processor. Pulse several times, stopping to scrape down the sides as needed until the coconut mixture is blended but still has texture. You should be able to pinch the filling and it will hold together, but still be a bit crumbly. 2. Take two tablespoons of the coconut mixture and form a bar shape, and place it on a parchment paper lined baking sheet, you should get about 8 bars. Or for coconut balls, take one tablespoon and form a ball, making about 16 balls. Pop the tray into the freezer to firm up for 10 minutes. 3. While the coconut is firming up, melt the chocolate chips in a double boiler. When the coconut bars or balls have become firm, drop them into the melted chocolate one at a time and use a spoon and fork to cover the bar. Shake off excess chocolate then place back on the parchment-lined baking sheet. Repeat with all of the coconut bars. Pop in the fridge or freezer to set the chocolate. Once set, store bars in an air-tight container in the fridge for up to a week. I like my bars at room temperature best, so I take them out to warm up about 30 minutes before I want to enjoy them.', note:''},

    ]

    Dessert.deleteMany({})
        .then(deleteDesserts => {
            console.log('testing this function')
            Dessert.create(startDesserts)
                .then((data) => {
                    console.log('new seeded desserts', data)
                    db.close()
                })
                .catch(error => {
                    console.log(error)
                    db.close()
                 })
        }) 
}) 